-- TASK 1: CREATE A TABLE FOR BRANCH.
DROP TABLE IF EXISTS BRANCH;
CREATE TABLE BRANCH(
	branch_id VARCHAR(15) PRIMARY KEY,
	manager_id VARCHAR(15),
	branch_address VARCHAR(50),
	contact_no VARCHAR (15)
);

SELECT * FROM BRANCH;

DROP TABLE IF EXISTS EMPLOYEES;
CREATE TABLE EMPLOYEES(
	emp_id VARCHAR(15) PRIMARY KEY,
	emp_name VARCHAR(25),
	position VARCHAR(15),
	salary INT,
	branch_id VARCHAR(25)
);

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
	isbn VARCHAR(20) PRIMARY KEY,
	book_title VARCHAR(75),
	category VARCHAR(20),
	rental_price FLOAT,
	status VARCHAR(15),
	author VARCHAR(35),
	publisher VARCHAR(55)
);

DROP TABLE IF EXISTS MEMBERS;
CREATE TABLE MEMBERS (
	member_id VARCHAR(15) PRIMARY KEY,
	member_name VARCHAR(25),
	member_address VARCHAR (75),
	reg_date DATE
);

DROP TABLE IF EXISTS ISSUED_STATUS;
CREATE TABLE ISSUED_STATUS(
	issued_id VARCHAR(15) PRIMARY KEY,
	issued_member_id VARCHAR(15),
	issued_book_name VARCHAR(75),
	issued_date DATE,
	issued_book_isbn VARCHAR(25),
	issued_emp_id VARCHAR(15)
);

DROP TABLE IF EXISTS RETURN_STATUS;
CREATE TABLE RETURN_STATUS(
	return_id VARCHAR(15) PRIMARY KEY,
	issued_id VARCHAR(15),
	return_book_name VARCHAR(75),
	return_date DATE,
	return_book_isbn VARCHAR(20)
);

-- FOREING KEY.

ALTER TABLE BOOKS
	ALTER COLUMN CATEGORY TYPE VARCHAR(20);

ALTER TABLE ISSUED_STATUS
ADD CONSTRAINT FK_MEMBERS
FOREIGN KEY (ISSUED_MEMBER_ID)
REFERENCES MEMBERS(MEMBER_ID);

ALTER TABLE ISSUED_STATUS
ADD CONSTRAINT FK_BOOKS
FOREIGN KEY (ISSUED_BOOK_ISBN)
REFERENCES BOOKS(ISBN);

ALTER TABLE ISSUED_STATUS
ADD CONSTRAINT FK_EMPLOYEES
FOREIGN KEY (ISSUED_EMP_ID)
REFERENCES EMPLOYEES(EMP_ID);

ALTER TABLE EMPLOYEES
ADD CONSTRAINT FK_BRANCH
FOREIGN KEY (ISSUED_ID)
REFERENCES BRANCH(BRANCH_ID);

ALTER TABLE RETURN_STATUS
ADD CONSTRAINT FK_ISSUED_STATUS
FOREIGN KEY (ISSUED_ID)
REFERENCES ISSUED_STATUS(ISSUED_ID);